- id: arXiv:2403.17998
  type: paper
  description: paper Accepted by cvpr1014
  date: 2024-3-26
  image: images/projects/jiamian/t-mass.jpg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/Jiamian-Wang/T-MASS-text-video-retrieval
  tags:
    - vision-Language
    - retrieval
    - video
  repo: https://github.com/Jiamian-Wang/T-MASS-text-video-retrieval

- id: arXiv:2403.11299
  type: paper
  description: paper under-review
  date: 2024-3-17
  image: images/projects/guohao/sq-llava.jpg
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/heliossun/SQ-LLaVA
  tags:
    - vision-Language
    - LLM
    - generation
  repo: https://github.com/heliossun/SQ-LLaVA